name: MacOS CI
on: [push]

jobs:
  deploy-test:
    name: Grisp Toolchain Installation and Deployment Test
    runs-on: macos-latest
    strategy:
        matrix:
          otp: ['25', '26']

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Erlang and dependencies
        run: |
            brew install erlang@${{matrix.otp}}
            brew link erlang@${{matrix.otp}}
            curl -o /usr/local/bin/rebar3 https://s3.amazonaws.com/rebar3/rebar3
            chmod +x /usr/local/bin/rebar3

            mkdir -p ~/.config/rebar3
            rebar_config=$(cat << EOF
            {plugins, [
                rebar3_hex,
                rebar3_grisp
            ]}.
            EOF
            )
            echo "$rebar_config" > ~/.config/rebar3/rebar.config
            
      - name: Compile and Deploy
        # env:
        #     DIAGNOSTIC: 0
        #     DEBUG: 0
        run: |
            ./scripts/patch-otp-version ${{matrix.otp}}
            rebar3 compile
            rebar3 grisp deploy --force
